# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c220f1215f53609ba15d1e9ad80b95616d224b954210280c557bffe7d60cf5d2d75e582f6d626950c08f8d9c3ae9152cc5d304ddb93ec0e4b9ffbe35c1e4649

test:
  secret_key_base: f7e4bf619abfcddf5f174af9437af9bc121a09ede3be4aa538317a34694d3a6f3cae6790da8d614261bd692a009a8a3e3bbba3dbc5b83c2e7516698c0d366100

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
